# Generated by Django 2.2.9 on 2020-02-26 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deletedtrade',
            table='deleted_trade',
        ),
        migrations.CreateModel(
            name='EditedTrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edit_date', models.DateTimeField()),
                ('attribute_edited', models.CharField(choices=[('DT', 'date'), ('PR', 'product'), ('BP', 'buying party'), ('SP', 'selling party'), ('NA', 'notional amount'), ('NC', 'notional currency'), ('QT', 'quantity'), ('MD', 'maturity date'), ('UP', 'underlying price'), ('UC', 'underlying currency'), ('SP', 'strike price')], max_length=2)),
                ('old_value', models.CharField(max_length=16)),
                ('new_value', models.CharField(max_length=16)),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Trade')),
            ],
        ),
    ]
