# Generated by Django 2.2.9 on 2020-02-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedTradeField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_id', models.CharField(max_length=16)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(max_length=32)),
                ('old_value', models.CharField(max_length=64)),
                ('new_value', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'edited_trade_field',
            },
        ),
        migrations.AlterModelTable(
            name='deletedtrade',
            table='deleted_trade',
        ),
    ]
