# Generated by Django 2.2.9 on 2020-02-28 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editedtrade',
            name='trade_id',
        ),
        migrations.DeleteModel(
            name='DeletedTrade',
        ),
        migrations.DeleteModel(
            name='EditedTrade',
        ),
    ]
