# Generated by Django 2.2.9 on 2020-02-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200226_1437'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedTrade',
        ),
    ]
