# Generated by Django 2.2.9 on 2020-02-28 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200228_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedTrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('edit_date', models.DateTimeField()),
                ('attribute_edited', models.CharField(choices=[('PR', 'product'), ('BP', 'buying party'), ('SP', 'selling party'), ('NC', 'notional currency'), ('QT', 'quantity'), ('MD', 'maturity date'), ('UP', 'underlying price'), ('UC', 'underlying currency'), ('ST', 'strike price')], max_length=2)),
                ('old_value', models.CharField(max_length=32)),
                ('new_value', models.CharField(max_length=32)),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_trade', to='api.Trade')),
            ],
            options={
                'db_table': 'edited_trade',
            },
        ),
        migrations.CreateModel(
            name='DeletedTrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_trade', to='api.Trade')),
            ],
            options={
                'db_table': 'deleted_trade',
            },
        ),
    ]
