# Generated by Django 2.2.9 on 2020-02-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_deletedtrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditedTrade',
        ),
    ]
