# Generated by Django 2.2.9 on 2020-02-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_editedtrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditedTrade',
        ),
    ]
