# Generated by Django 2.2.9 on 2020-02-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_editedtrade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedTrade',
        ),
    ]
