# Generated by Django 2.2.9 on 2020-02-26 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_deletedtrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedTrade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(auto_now=True)),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Trade')),
            ],
            options={
                'db_table': 'deleted_trade',
            },
        ),
    ]
