# Generated by Django 2.2.9 on 2020-02-28 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_deletedtrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletedtrade',
            name='trade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_trade', to='api.Trade'),
        ),
        migrations.AlterField(
            model_name='editedtrade',
            name='trade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_trade', to='api.Trade'),
        ),
    ]
