# Generated by Django 2.2.9 on 2020-02-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200228_0656'),
        ('api', '0011_auto_20200228_0121'),
    ]

    operations = [
    ]
