# Generated by Django 2.2.9 on 2020-02-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20200228_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditedTradeField',
        ),
    ]
