# Generated by Django 2.2.9 on 2020-02-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_editedtradefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedtrade',
            name='new_value',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='editedtrade',
            name='old_value',
            field=models.CharField(max_length=32),
        ),
    ]
