# Generated by Django 2.2.9 on 2020-02-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200228_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editedtrade',
            name='attribute_edited',
            field=models.CharField(choices=[('PR', 'product'), ('BP', 'buying party'), ('SP', 'selling party'), ('NC', 'notional currency'), ('QT', 'quantity'), ('MD', 'maturity date'), ('UP', 'underlying price'), ('UC', 'underlying currency'), ('ST', 'strike price')], max_length=2),
        ),
    ]
