# Generated by Django 2.2.9 on 2020-02-28 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200228_2013'),
        ('api', '0003_deletedtrade_editedtrade'),
    ]

    operations = [
    ]
