# Generated by Django 2.2.9 on 2020-03-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20200228_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCorrection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('erroneous_attribute', models.CharField(choices=[('QT', 'quantity'), ('UP', 'underlying price'), ('ST', 'strike price')], max_length=2)),
                ('old_value', models.CharField(max_length=32)),
                ('new_value', models.CharField(max_length=32)),
                ('change_type', models.CharField(choices=[('USER', 'user'), ('SYTM', 'system')], max_length=5)),
                ('date', models.DateTimeField()),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrected_trade', to='api.Trade')),
            ],
            options={
                'db_table': 'attribute_correction',
            },
        ),
        migrations.CreateModel(
            name='ErroneousTradeAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('erroneous_attribute', models.CharField(choices=[('QT', 'quantity'), ('UP', 'underlying price'), ('ST', 'strike price')], max_length=2)),
                ('erroneous_value', models.CharField(max_length=20)),
                ('lower_range', models.CharField(max_length=20)),
                ('upper_range', models.CharField(max_length=20)),
                ('mean', models.CharField(max_length=20)),
                ('trade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erroneous_trade', to='api.Trade')),
            ],
            options={
                'db_table': 'erroneous_trade_attribute',
            },
        ),
    ]
