# Generated by Django 2.2.9 on 2020-03-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_erroneoustradeattribute_fieldcorrection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erroneoustradeattribute',
            old_name='trade_id',
            new_name='trade',
        ),
        migrations.RenameField(
            model_name='fieldcorrection',
            old_name='trade_id',
            new_name='trade',
        ),
    ]
